### ISSUE TITLE
Ask a running code error problem

### ISSUE THREAD

**Issue by love112358** [sharif-apu/LDR2HDR_NTIRE21#1]
Hello, when I run this project code in your way, there is a problem. I don't know how to solve it. Can you help me：

 ai p main.py -i -s /source/code/SuperResolution/twostageHDR_NTIRE21/images -d /source/d3/super_resolution/model/twostageHDR_NTIRE21/outputimage
Traceback (most recent call last):
  File "main.py", line 37, in <module>
    twostageHDR(config).modelInference(options.sourceDir, options.resultDir)
  File "/source/code/SuperResolution/twostageHDR_NTIRE21/mainModule/twostageHDR.py", line 70, in __init__
    self.attentionNet = ResMKHDR().to(self.device)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 443, in to
    return self._apply(convert)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 203, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 225, in _apply
    param_applied = fn(param)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 441, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
  File "/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py", line 149, in _lazy_init
    _check_driver()
  File "/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py", line 47, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by sharif-apu** [comment]
Hi there,
It seems like issues have arrived due to the CUDA compilation error. You may refer to the following thread: https://github.com/pytorch/pytorch/issues/30664. Also, to avoid any version mismatch issues, I'll suggest you use the same versions (of packages), which we've suggested in the pre-requisite section.
